<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreInvoiceRequest;
use App\Http\Requests\UpdateInvoiceRequest;
use App\Http\Resources\InvoiceCollection;
use App\Http\Resources\InvoiceResource;
use App\Models\Invoice;
use Illuminate\Http\Request;

final class InvoiceController extends Controller
{
    /**
     * @param Request $request
     * @return InvoiceCollection
     */
    public function index(Request $request): InvoiceCollection
    {
        $perPage = $request->integer('per_page', 10);
        $invoices = Invoice::latest()->paginate($perPage);

        return new InvoiceCollection($invoices);
    }

    /**
     * @param Invoice $invoice
     * @return InvoiceResource
     */
    public function show(Invoice $invoice): InvoiceResource
    {
        return new InvoiceResource($invoice);
    }

    /**
     * @param StoreInvoiceRequest $request
     * @return InvoiceResource
     */
    public function store(StoreInvoiceRequest $request): InvoiceResource
    {
        $data = $request->validated();
        
        $invoice = Invoice::create($data);
        // Fetch default values generated by the database (like status and currency)
        $invoice->refresh();

        return new InvoiceResource($invoice);
    }

    /**
     * @param UpdateInvoiceRequest $request
     * @param Invoice $invoice
     * @return InvoiceResource
     */
    public function update(UpdateInvoiceRequest $request, Invoice $invoice): InvoiceResource
    {
        $data = $request->validated();
        
        $invoice->update($data);

        return new InvoiceResource($invoice);
    }
}
